export const locationData: any[] = [
  { id: 2, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 1, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 3, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 4, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 5, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 6, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 7, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 8, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 9, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 10, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 11, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 12, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
  { id: 13, name: "Earth (C-137)", dimension: "C-137", type: "Planet" },
];
