export const episodeData: any[] = [
  {
    id: 2,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 1,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 3,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 4,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 5,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 6,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 7,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 8,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 9,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 10,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 11,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 12,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
  {
    id: 13,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "SE01E01",
    characters: "",
    url: "",
    created: "",
  },
];
